#!/bin/sh -e


if [ "$2" ] && dpkg --compare-versions "$2" lt 2.2; then
    if [ -x "/etc/init.d/thomsoft-cloud-api" ]; then
        if [ -x /usr/sbin/invoke-rc.d ]; then
                invoke-rc.d thomsoft-cloud-api stop || true
        else
                /etc/init.d/thomsoft-cloud-api stop || true
        fi
    fi
fi

case "$1" in
	install)
		;;
	upgrade)
		;;
	*)
		;;
esac


